### ISSUE TITLE
Maybe workflow schedule has been stopped.

### ISSUE THREAD

**Issue by snaka** [Songmu/homebrew-tap#40]
![image](https://github.com/Songmu/homebrew-tap/assets/19329/05af4e2d-dfb9-4e8f-9986-81a5baced7e9)

I am not sure I understand it well,
It may be necessary to have some action performed in the repository to make the schedule effective again.

**Comment by Songmu** [comment]
Thanks for letting me know! I have enabled the workflow and merged the following.

https://github.com/Songmu/homebrew-tap/pull/41

**Comment by snaka** [comment]
Thanks!
